version: '3.0'
services:
  mysql:
    image: mysql:5.7
    ports: ['3306:3306']
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=blackout_advisor
      - MYSQL_USER=symfony
      - MYSQL_PASSWORD=1234
  php:
    build: ./docker/php
    ports: ['9000:9000']
    depends_on:
      - mysql
    links:
      - mysql
    volumes:
      - ./app/:/var/www/app:cached
    working_dir: /var/www/app
    environment:
      TIMEZONE: Europe/Paris
      COMPOSER_ALLOW_SUPERUSER: 1
  nginx:
    build: ./docker/nginx
    ports:
      - 80:80
    links:
      - php
    volumes:
      - ./logs/nginx:/var/log/nginx:cached
      - ./app/:/var/www/app:cached
